config/routes.rb
Ifiwasking::Application.routes.draw do
  resources :proclamations do
    member do
      post :vote_up
    end
  end

  devise_for :users
  resources :users
  
  resources :votes

  
  root :to => "proclamations#index"

  get 'maps/' => 'maps#index'
  get 'maps/show' => 'maps#show'
  get 'mapstest/' => 'maps#test'
    

  

end

app/models/proclamation.rb
class Proclamation < ActiveRecord::Base
    #TODO use validations?
    #validates :user_id, presence: true

    belongs_to :user
    has_many :votes

    #thumbs_up config
    acts_as_voteable

    #geocoder config
    # geocoded_by :address
    # after_validation :geocode

    # reverse_geocoded_by :latitude, :longitude
    # after_validation :reverse_geocode  # auto-fetch address
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_username

  has_many :proclamations
  has_many :votes

  acts_as_voter
  
  private

  def generate_username
    self.username = self.email.split("@")[0]
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base


  belongs_to :proclamation
  belongs_to :user
  

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
    @latlng = nil;
    render :index
  end

  def test
    render :maps
  end

  def show

    @proclamations = Proclamation.all

    @hash = Gmaps4rails.build_markers(@proclamations) do |proclamation, marker|
        marker.lat proclamation.latitude.to_f
        marker.lng proclamation.longitude.to_f
    end
        
    render :show
  end


end

app/controllers/proclamations_controller.rb
class ProclamationsController < ApplicationController
  before_action :set_proclamation, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index]

  # GET /proclamations
  def index
    @proclamations = Proclamation.all
    @proclamation = Proclamation.new
  end

  # GET /proclamations/1
  def show
  end

  #implements  voting with thumbs_up
  #catches ActiveRecord error if user already voted for proclamation and redirects to error page.
  def vote_up
    begin
      current_user.vote_for(@proclamation = Proclamation.find(params[:id]))
      render :show
    rescue ActiveRecord::RecordInvalid
      render :error
    end
  end

  # GET /proclamations/new
  def new
    @proclamation = Proclamation.new
  end

  # GET /proclamations/1/edit
  def edit
  end

  # POST /proclamations
  def create
    @proclamation = Proclamation.new(proclamation_params)
    @proclamation.user = current_user

    respond_to do |format|
      if @proclamation.save
        format.html { redirect_to @proclamation, notice: 'Proclamation was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /proclamations/1

  def update
    respond_to do |format|
      if @proclamation.update(proclamation_params)
        format.html { redirect_to @proclamation, notice: 'Proclamation was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /proclamations/1
  
  def destroy
    @proclamation.destroy
    respond_to do |format|
      format.html { redirect_to proclamations_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proclamation
      @proclamation = Proclamation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proclamation_params
      params.require(:proclamation).permit(:proclamation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user != @user
      redirect_to users_path
    end
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /users/1
   def update
    if current_user != @user
      redirect_to users_path
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /users/1
  def destroy
    if current_user != @user
      redirect_to users_path
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to '/' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email)
    end

    # def user_authorization
    #   binding.pry
    #   redirect_to(root_url) unless current_user.id == params[:id]
    # end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  #implements leaderboard
  def index
    @ranked = Proclamation.plusminus_tally
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proclamations_helper.rb
module ProclamationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ifiwasking</title>
  <%= stylesheet_link_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Raleway|Vidaloka' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
<body>
  <div class="container sixteen columns">
  
    <%= image_tag "crown.jpg" %>

    <div class="nav">
        <ul>
          <li><%= link_to 'proclamations', proclamations_path %></li>
          <li><%= link_to 'users', users_path %></li>   
          <li><%= link_to 'leaderboard', votes_path %></li>
          <li>experimental: <%= link_to 'mapped', maps_show_path %> | <%= link_to 'geolocate', maps_path %></li>

            <%if user_signed_in? %>
                <li>signed in as <%= current_user.email %>
                <%= link_to "sign out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to "sign in", new_user_session_path %> Or <%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %> 
 
       
        </ul>

    </div>
      
    
    <%= yield %>
  
  </div>
</body>

</html>

app/views/maps/index.html.erb
<h1> experimental obtaining gps via browser </h1>

<meta name="viewport" content="width=620" />
<title>geolocation</title>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <article>
      <p>Finding your location: <span id="status">checking...</span></p>
    </article>

<script>
  getGeoLocation();
</script>

<div id="test"> </div>

app/views/maps/show.html.erb
<h1> experimental plotting proclamations on map </h1>
<div style='width: 800px; border:1px solid #000;'>
    <div id="map" style='width: 800px; height: 400px;'>
    </div>          
</div>

<script>
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      });
</script>

app/views/proclamations/_form.html.erb
<div>
  <%= form_for(@proclamation) do |f| %>
    <%= f.text_field :proclamation, :class=> "eleven columns", placeholder: "your best idea goes here..."%>
    <%= f.submit 'Proclaim', :class => 'full-width button' %>
  <% end %>
</div>

app/views/proclamations/_single.html.erb
<div class="proclamation">
  <p>
    <%= proclamation.proclamation %> by <%= link_to proclamation.user.username, proclamation.user %>
  </p>
  
  <div class="link">        
    <%= link_to('Vote It Up!', vote_up_proclamation_path(proclamation), :method => :post) %>
  </div>  
    

  <% if current_user == proclamation.user %>
    <p>
      <%= link_to 'Edit', edit_proclamation_path(proclamation) %>
      <%= link_to 'Destroy', proclamation, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

</div>

app/views/proclamations/edit.html.erb
<h1>Editing proclamation</h1>

<%= render 'form' %>

<%= link_to 'Show', @proclamation %> |
<%= link_to 'Back', proclamations_path %>

app/views/proclamations/error.html.erb
<h1> THERE WAS A PROBLEM </h1>

<p>
You probably already voted for that.  
Do something different for christs sake.
</p>

<h1><%= link_to 'Get Proclamated!', proclamations_path %></h1>

app/views/proclamations/index.html.erb
<div class="title">
    <h3>If I Were King...</h3>
    <%= render 'form' %>
</div>

<div>
    <% @proclamations.each do |proclamation| %>
        <div class="four columns">
          <%= render 'single', proclamation: proclamation %>
        </div>
    <% end %>
</div>

app/views/proclamations/new.html.erb
<h1>New proclamation</h1>

<%= render 'form' %>

<!-- 
<%= link_to 'Back', proclamations_path %>

 -->

app/views/proclamations/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'single', proclamation: @proclamation %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user == user %>
          <td>...<%= link_to 'Edit', edit_user_path(user) %> </td>
          <td>...<%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Username:
  <%= @user.username %>
</p>

<p>
  Email:
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<p>
</p>

<h2>All These Proclamations Are Yours</h2>

    <% @user.proclamations.each do |proclamation| %>
      

        <p><%= proclamation.proclamation %></p>
        <p>
        <%= link_to 'Show', proclamation %>

        <% if current_user == proclamation.user %>
          | <%= link_to 'Edit', edit_proclamation_path(proclamation) %> |
          <%= link_to 'Destroy', proclamation, method: :delete, data: { confirm: 'Are you sure?' } %> 
        <% end %>
      </p>
    <% end %>

app/views/votes/index.html.erb
<% if current_user == @ranked.first.user %>
  <h1> ON TOP OF THE WORLD, BABY </h1>
<% else %>
  <h1> Leaderboard </h1>
<% end %>

<% @ranked.each do |p| %>
  <p>
  <strong><%= p.proclamation %></strong> from <%= p.user.username %> <%= p.votes_for %> votes.
  <%= link_to 'Show', p %>
  </p>
<% end %>

app/views/votes/new.html.erb
<%= form_for(@vote) do |f| %>
  <div class="field">
    <%= f.label :vote %><br>
    <%= f.check_box :vote %>
  </div>

  <div class ="params">
    proclamation_id is <%= params[:proclamation_id] %>
  </div>

  <%= text_field_tag(params[:proclamation_id]) %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>